### ISSUE TITLE
关于Lorenz在aistudio上的断点续训练1 

### ISSUE THREAD

**Issue by xiaoniv** [PaddlePaddle/PaddleScience#1034]
### bug 描述 bug description

你好。我在aistudio上跑通了那个Lorenz例子，想试下断点继续训练。我跑了10个epoch，按了停止退出codelab。然后重新进入codelab,安装paddlescience，再运行训练之前的代码。我想用初始化直接读取checkpoint，就运行以下代码。
```python
OUTPUT_DIR = "./output/lorenz_transformer"
cp_path = f"{OUTPUT_DIR}/checkpoints"

new_solver = ppsci.solver.Solver(
    model=model,
    constraint=constraint,
    output_dir=OUTPUT_DIR,  # Added output_dir
    optimizer=optimizer,
    lr_scheduler=lr_scheduler,
    eval_during_train=True,
    eval_freq=50,
    validator=validator,
    visualizer=visualizer,
    checkpoint_path=cp_path,# try to active load checkpoint in init
)
```
得到报错AttributeError: 'Solver' object has no attribute 'loss_aggregator'，显式给loss_aggregator赋值也不行。

**Comment by HydrogenSulfate** [comment]
十分抱歉，经过确认这是我写的一个BUG，我已经在 #1038 中进行了修复并添加了单测，待CI通过后我会尽快合入，你可以等待代码合入后拉取一下最新develop分支的代码，或者直接按照PR里的修改两处代码即可。

**Comment by HydrogenSulfate** [comment]
@xiaoniv 你好，修复PR已合入，重新拉取develop的代码即可
