### ISSUE TITLE
Set up a simulation domain with holes

### ISSUE THREAD

**Issue by ma-sadeghi** [PaddlePaddle/PaddleScience#174]
Is there a way to set up a simulation domain, for example a rectangle, with some holes? Thanks!

**Comment by Liu-xiandong** [comment]
Hi, we currently support this feature. If you want to get a  cube with a triangular hole, it is implemented as follows:
```
import paddlescience as psci
import numpy as np
import paddle

# triangle
vertices = np.array([[3, 3, 0], [7, 3, 0], 
            [5, 7, 0], [3, 3, 0.5], 
            [7, 3, 0.5], [5, 7, 0.5]])
# mesh faces 
# Right-hand rule
faces = np.hstack(
    [
        [3, 0, 2, 1],  # triangle
        [3, 3, 4, 5],  # triangle
        [4, 0, 3, 5, 2], # square
        [4, 1, 2, 5, 4], # square
        [4, 0, 1, 4, 3],  # square
    ]
)

triangle = psci.geometry.PolyData(vertices, faces)

geo = psci.geometry.Rectangular(origin=(0, 0, 0), extent=(10, 10, 0.5))

geo = geo - triangle

geo.add_boundary(name="inlet", criteria=lambda x, y, z: abs(x) < 1e-5)
geo.add_boundary(name="outlet", criteria=lambda x, y, z: abs(x - 10) < 1e-5)
geo.add_boundary(name="triangle", filename=triangle)

# discretize geometry
geo_disc = geo.discretize(method="quasi_sobol", npoints= 3000)

psci.visu.save_vtk(filename="out", geo_disc=geo_disc)
```
Note that this function only supports three-dimensional objects.

**Comment by ma-sadeghi** [comment]
@Liu-xiandong Thank you for your reply and the code snippet.

Let me take it one step futher: I'm eventually interested in solving a PDE inside a voxel image (a binary image that could represent for instance a porous rock), like the one below:

```bash
1 0 0 1 1 0
1 1 0 0 1 1
0 1 0 1 1 0
1 1 1 0 1 1
1 1 0 0 1 1
1 1 0 1 1 0
```

From what I understand, it should be possible in principle to generalize the method you proposed by treating the 0s (assuming 1s as the simulation domain) as small rectangular blocks, and then subtracting them from the original domain (is that correct?), but I guess that might be a slow process especially for large images. I'd really appreciate it if you let me know if you can think of a workaround. Thanks once again!

**Comment by Liu-xiandong** [comment]
> large image

@ma-sadeghi Hi, I think this method is feasible. Think of the entire image as a cube with the 0s as holes to dig out. The more troublesome thing is to map 0 to hole, which involves some troublesome mapping and indexing operations.

**Comment by HydrogenSulfate** [comment]
你好，PaddleScience 1.0 正式版已经发布，提供了全新设计的 API 供开发使用，可以参考用户文档进行开发
https://paddlescience-docs.readthedocs.io/zh/latest/
