### ISSUE TITLE
loss with weight

### ISSUE THREAD

**Issue by Traiiicy** [PaddlePaddle/PaddleScience#204]
请问如果我想探究损失函数内的不同权重对结果的影响，应该如何修改loss呢

**Comment by Jkzhangyb** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/4178470?channelType=0&channel=0， 可以参考这个例子

**Comment by HydrogenSulfate** [comment]
你好，PaddleScience 1.0 正式版已经发布，提供了全新设计的 API 供开发使用，可以参考用户文档进行开发
https://paddlescience-docs.readthedocs.io/zh/latest/
