### ISSUE TITLE
requirements.txt中pyvista和pysdf在windows环境无法安装

### ISSUE THREAD

**Issue by Jkzhangyb** [PaddlePaddle/PaddleScience#206]
您好，paddlescience库中的pysdf和pyvista无法在windows环境下安装（外部同学用的是pycharm）有啥解决方法呢？

**Comment by HydrogenSulfate** [comment]
[win10 pyvista以及pysdf安装.pdf](https://github.com/PaddlePaddle/PaddleScience/files/10302391/win10.pyvista.pysdf.pdf)
