### ISSUE TITLE
测试高阶微分算子方板算例报错AttributeError: 'TensorShape' object has no attribute 'count'

### ISSUE THREAD

**Issue by Liueotile3333** [PaddlePaddle/PaddleScience#234]
File "C:/Users/UESTC_SAA/Desktop/High Order/elasticPlate_Rectangular.py", line 298, in <module>
    loss_weights=[1, 100, 100, 100, 100, 100, 100, 100, 100])
  File "C:\Users\UESTC_SAA\anaconda3\envs\DeepXDE\lib\site-packages\deepxde\utils\internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\UESTC_SAA\anaconda3\envs\DeepXDE\lib\site-packages\deepxde\model.py", line 131, in compile
    self._compile_tensorflow_compat_v1(lr, loss_fn, decay, loss_weights)
  File "C:\Users\UESTC_SAA\anaconda3\envs\DeepXDE\lib\site-packages\deepxde\model.py", line 176, in _compile_tensorflow_compat_v1
    losses_train = losses(self.data.losses_train)
  File "C:\Users\UESTC_SAA\anaconda3\envs\DeepXDE\lib\site-packages\deepxde\model.py", line 163, in losses
    self.net.targets, self.net.outputs, loss_fn, self.net.inputs, self
  File "C:\Users\UESTC_SAA\anaconda3\envs\DeepXDE\lib\site-packages\deepxde\data\data.py", line 13, in losses_train
    return self.losses(targets, outputs, loss_fn, inputs, model, aux=aux)
  File "C:\Users\UESTC_SAA\anaconda3\envs\DeepXDE\lib\site-packages\deepxde\data\pde.py", line 127, in losses
    f = self.pde(inputs, outputs_pde)
  File "C:/Users/UESTC_SAA/Desktop/High Order/elasticPlate_Rectangular.py", line 228, in pde
    result = paddle.concat(x=[y, Mx, My, Mxy, Qx, Qy], axis=-1)
  File "C:\Users\UESTC_SAA\anaconda3\envs\DeepXDE\lib\site-packages\paddle\tensor\manipulation.py", line 1120, in concat
    input = [t for t in input if t.shape.count(0) == 0]
  File "C:\Users\UESTC_SAA\anaconda3\envs\DeepXDE\lib\site-packages\paddle\tensor\manipulation.py", line 1120, in <listcomp>
    input = [t for t in input if t.shape.count(0) == 0]
AttributeError: 'TensorShape' object has no attribute 'count'

进程已结束,退出代码1

input = x
    if in_dygraph_mode():
        if isinstance(axis, Variable):
            axis = axis.item(0)
        if not isinstance(input, Variable):
            **input = [t for t in input if t.shape.count(0) == 0]**
        return _C_ops.concat(input, axis)
请问这是什么问题

**Comment by HydrogenSulfate** [comment]
方便发一下运行命令吗

**Comment by Liueotile3333** [comment]
![image](https://user-images.githubusercontent.com/109189160/228996644-ee51d599-8923-4353-9547-f9f9e9b65dfd.png)
![image](https://user-images.githubusercontent.com/109189160/228996699-016c2f84-46a2-4d94-86ac-8003425f4f93.png)
![image](https://user-images.githubusercontent.com/109189160/228996772-6c5660bb-01de-4dd9-b879-44c1e8404db4.png)

**Comment by Liueotile3333** [comment]
![image](https://user-images.githubusercontent.com/109189160/228997255-c12f318f-b45c-49a9-8741-192450f61a04.png)

**Comment by HydrogenSulfate** [comment]
> ![image](https://user-images.githubusercontent.com/109189160/228996644-ee51d599-8923-4353-9547-f9f9e9b65dfd.png) ![image](https://user-images.githubusercontent.com/109189160/228996699-016c2f84-46a2-4d94-86ac-8003425f4f93.png) ![image](https://user-images.githubusercontent.com/109189160/228996772-6c5660bb-01de-4dd9-b879-44c1e8404db4.png)

看起来是你运行的后端没有选择paddle，请在你的运行命令前面加上 `DDE_BACKEND=BACKEND`
```
DDE_BACKEND=BACKEND python xxx.py
```

**Comment by Liueotile3333** [comment]
@HydrogenSulfate 貌似并不是运行的后端没有选择paddle的问题，我在ipynb中运行CPU版本也会出现问题，但是GPU版本就没有这个问题

**Comment by Liueotile3333** [comment]
@HydrogenSulfate 是这个问题，十分感谢，请问有没有paddle的ai for science板块交流群么？

**Comment by HydrogenSulfate** [comment]
> 

提供一下邮箱地址，联系方式邮件发送给你

**Comment by Liueotile3333** [comment]
@HydrogenSulfate 感谢

**Comment by HydrogenSulfate** [comment]
发自我的手机-------- 原始邮件 --------发件人： Liueotile3333 ***@***.***>日期： 2023年4月19日周三 下午4:49收件人： PaddlePaddle/PaddleScience ***@***.***>抄送： HydrogenSulfate ***@***.***>, Mention ***@***.***>主    题： Re: [PaddlePaddle/PaddleScience] 测试高阶微分算子方板算例报错AttributeError: 'TensorShape' object has no attribute 'count' (Issue #234)
@HydrogenSulfate 感谢

**Comment by Liueotile3333** [comment]
@HydrogenSulfate 你好，可以再发一下paddle的ai for science板块交流群联系方式么？邮箱是xll1901037@nuaa.edu.cn，刚才您回的邮件没有显示。谢谢
![image](https://user-images.githubusercontent.com/109189160/233050776-029657bd-8928-4d0b-a4f0-b93431f0ac0e.png)

**Comment by HydrogenSulfate** [comment]
***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年4月19日 18:42
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [PaddlePaddle/PaddleScience] 测试高阶微分算子方板算例报错AttributeError: 'TensorShape' object has no attribute 'count' (Issue #234)
        
      
    
  

@HydrogenSulfate 你好，可以再发一下paddle的ai for ***@***.***，刚才您回的邮件没有显示。谢谢
