### ISSUE TITLE
2d圆柱绕流算例中用于训练的dataset的疑问

### ISSUE THREAD

**Issue by jiangzhangze** [PaddlePaddle/PaddleScience#293]
datasets中的各个csv文件分别代表什么呢？
domain_cylinder.csv，domain_inlet.csv，domain_outlet.csv分别包含了圆柱上，入口，出口的网格和初始时刻数据，domain_train.csv包含整个流场的初始时刻.这样理解对吗？
在initial文件夹中的csv，又是哪个时刻的流场数据呢，因为我看ic0.1.csv中的速度和压力不是初始时刻的数据。
在probes文件夹中的50个probes文件又是代表的什么.

如果我想自己生成数据，放到脚本中直接来训练，也应该按照这个格式吗

**Comment by HydrogenSulfate** [comment]
> datasets中的各个csv文件分别代表什么呢？ domain_cylinder.csv，domain_inlet.csv，domain_outlet.csv分别包含了圆柱上，入口，出口的网格和初始时刻数据，domain_train.csv包含整个流场的初始时刻.这样理解对吗？ 在initial文件夹中的csv，又是哪个时刻的流场数据呢，因为我看ic0.1.csv中的速度和压力不是初始时刻的数据。 在probes文件夹中的50个probes文件又是代表的什么.
> 
> 如果我想自己生成数据，放到脚本中直接来训练，也应该按照这个格式吗

数据集已经上传完毕，可以按照以下命令运行 cylinder2d_unsteady_Re100 案例

``` sh
python download_dataset.py
python cylinder2d_unsteady_Re100.py
```

**Comment by jiangzhangze** [comment]
Hi @HydrogenSulfate .谢谢您的回复，事实上我想基于自己计算的数据来训练，想知道关于自己生成数据集有教程之类的吗

**Comment by HydrogenSulfate** [comment]
> Hi @HydrogenSulfate .谢谢您的回复，事实上我想基于自己计算的数据来训练，想知道关于自己生成数据集有教程之类的吗

如果想自己训练的话，可以参照训练数据的格式（案例里用的是csv文件，可以直接用excel打开查看，或者也可以用.mat储存数据），最关键的就是最终是要把数据离散化成一个一个点，然后加载进来训练。

**Comment by cheercao** [comment]
在Windows下使用cpu的开发版本，运行文件cylinder2d_unsteady_Re100报错AttributeError: module 'paddle.optimizer' has no attribute 'LBFGS'，是由于飞浆版本的原因吗？是CPU版本没有只有GPU版本有这个属性吗？我的paddle是：paddlepaddle==0.0.0，cpu版本。

**Comment by HydrogenSulfate** [comment]
> 在Windows下使用cpu的开发版本，运行文件cylinder2d_unsteady_Re100报错AttributeError: module 'paddle.optimizer' has no attribute 'LBFGS'，是由于飞浆版本的原因吗？是CPU版本没有只有GPU版本有这个属性吗？我的paddle是：paddlepaddle==0.0.0，cpu版本。

建议先卸载一下本地的paddle，然后去官网安装develop版paddle，我在windows机器上试了一下是可以运行的

![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/ccd5b40e-5be4-4372-ad07-ef1810ace3bb)

**Comment by cheercao** [comment]
感谢，重新安装paddle之后问题已解决

**Comment by cheercao** [comment]
感谢，重新安装paddle之后问题已解决

**Comment by HydrogenSulfate** [comment]
> 感谢，重新安装paddle之后问题已解决

paddle develop版本为快速迭代版本，版本号都是0.0.0，所以是通过commit号 `paddle.version.commit` 对应的paddle commit日期来看版本的新旧，当commit号对应的commit日期（在paddle仓库中直接搜commit号就能搜到commit日期）比较老，意味着它是老的develop，可能存在功能缺失

**Comment by jiangzhangze** [comment]
你好 @HydrogenSulfate ，训练数据中的domain_train.csv和ic0.1.csv分别代表的是什么数据

**Comment by HydrogenSulfate** [comment]
> 你好 @HydrogenSulfate ，训练数据中的domain_train.csv和ic0.1.csv分别代表的是什么数据

`domain_train.csv` 是一个时刻的二维内部点坐标数据（example 代码中会被 `TimeXGeometry` 接受，复制成 T 份相同的数据变成时间-空间的三维坐标数据），这些点主要用于计算方程残差约束（作为损失函数的一项）；
ic0.1.csv 是一个时刻（初始时刻t0）的内部点坐标数据，用于初值约束

**Comment by jiangzhangze** [comment]
@HydrogenSulfate 
 domain_train.csv中的数据看起来似乎是初始时刻的数据？因为除了速度边界每个点对应的速度和压力都是0；
ic0.1.csv 像是某个时刻的数据，因为其中的点速度和压力都不像是初始时刻的。
![domain_train](https://github.com/PaddlePaddle/PaddleScience/assets/99314760/76b924b4-a987-4507-93b6-04a8d8bbded2)
![ic0 1](https://github.com/PaddlePaddle/PaddleScience/assets/99314760/972704d6-82bd-4254-922b-89c1ea16602a)

**Comment by HydrogenSulfate** [comment]
> @HydrogenSulfate domain_train.csv中的数据看起来似乎是初始时刻的数据？因为除了速度边界每个点对应的速度和压力都是0； ic0.1.csv 像是某个时刻的数据，因为其中的点速度和压力都不像是初始时刻的。 ![domain_train](https://user-images.githubusercontent.com/99314760/243273504-76b924b4-a987-4507-93b6-04a8d8bbded2.PNG) ![ic0 1](https://user-images.githubusercontent.com/99314760/243273539-972704d6-82bd-4254-922b-89c1ea16602a.PNG)

`domain_train.csv` 这个文件其实只用到了里面的 x 和 y，uvp数据并没有使用，所以和它所处的时刻没关系，
然后 `ic0.1.csv` 的uvp非0，是因为我们这个案例里选取的初始时刻并不是 0 时刻，而是之后的一个时刻 `TIME_START`，而本案例代码只是保证了 `domain_train.csv` 所用的时刻 T 在 `TIME_START` 之后。

**Comment by jiangzhangze** [comment]
使用t=0的数据构造IC时，是不是要用该时间段的最后时刻来构造domain_train.csv

**Comment by jiangzhangze** [comment]
> > @HydrogenSulfate domain_train.csv中的数据看起来似乎是初始时刻的数据？因为除了速度边界每个点对应的速度和压力都是0； ic0.1.csv 像是某个时刻的数据，因为其中的点速度和压力都不像是初始时刻的。 ![domain_train](https://user-images.githubusercontent.com/99314760/243273504-76b924b4-a987-4507-93b6-04a8d8bbded2.PNG) ![ic0 1](https://user-images.githubusercontent.com/99314760/243273539-972704d6-82bd-4254-922b-89c1ea16602a.PNG)
> 使用t=0的数据构造IC时，是不是要用该时间段的最后时刻来构造domain_train.csv
> 相当于我们模拟了某一个时间段（时间窗口）的2D流场，只是这个时间窗口的起始点不一定是0而已，如果是你自己的数据，完全可以尝试用t=0的数据去构造IC

**Comment by jiangzhangze** [comment]
> > @HydrogenSulfate domain_train.csv中的数据看起来似乎是初始时刻的数据？因为除了速度边界每个点对应的速度和压力都是0； ic0.1.csv 像是某个时刻的数据，因为其中的点速度和压力都不像是初始时刻的。 ![domain_train](https://user-images.githubusercontent.com/99314760/243273504-76b924b4-a987-4507-93b6-04a8d8bbded2.PNG) ![ic0 1](https://user-images.githubusercontent.com/99314760/243273539-972704d6-82bd-4254-922b-89c1ea16602a.PNG)
> 
> 相当于我们模拟了某一个时间段（时间窗口）的2D流场，只是这个时间窗口的起始点不一定是0而已，如果是你自己的数据，完全可以尝试用t=0的数据去构造IC

使用t=0的数据构造IC时，是不是要用该时间段的最后时刻来构造domain_train.csv

**Comment by HydrogenSulfate** [comment]
> 

举一个简单的例子，假如我想模拟一段离散时刻 $[t_0, t_1, ..., t_n]$ 的流场状态，那么就用 $t_0$ 数据作为初始时刻数据构造约束，$[t_1, ..., t_n]$ 时刻的数据作为方程数据构造约束

**Comment by cheercao** [comment]
请问有pytorch版本的代码吗？想对比学习一下

**Comment by HydrogenSulfate** [comment]
> 请问有pytorch版本的代码吗？想对比学习一下

没有提供pytorch代码，可以在 https://paddlescience-docs.readthedocs.io/zh/latest/zh/examples/cylinder2d_unsteady/ 跳转到 AIStudio 上运行该案例的代码

**Comment by cheercao** [comment]
运行代码会报错
![image](https://github.com/PaddlePaddle/PaddleScience/assets/60064870/8a3357ba-9ed4-4d0d-8e6b-59879fde28cc)

**Comment by HydrogenSulfate** [comment]
> 运行代码会报错 ![image](https://user-images.githubusercontent.com/60064870/243635384-8a3357ba-9ed4-4d0d-8e6b-59879fde28cc.png)

哦这里应该是变量没改成大写的原因，现在应该可以了，可以再试一下
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/444c45ce-1c27-4d94-b76c-3f130781e90e)

**Comment by cheercao** [comment]
感谢

**Comment by cheercao** [comment]
@HydrogenSulfate 请问代码中构建的计算域我可以理解为一个是微分方程约束的计算域也就是微分方程的一些随机取值，也就是说用来训练，还有一个计算域就是用整个时间的数据来测试训练的情况。我这么理解对吗？
![image](https://github.com/PaddlePaddle/PaddleScience/assets/60064870/40ce7f55-c08c-4c29-87cc-cebf7cb50ca0)

**Comment by HydrogenSulfate** [comment]
> 

计算域是一个比较抽象的概念，在 paddlescience 里一般指 **包含所研究问题的取值范围的区域**，可以是一个连续的几何，然后训练的时候会在这个连续的几何上进行采样得到训练/测试点；也可以是离散的几何（点云），训练的时候直接从点云中随机选取数据作为训练/测试点。

**Comment by cheercao** [comment]
比如我构建了一个训练的计算域，我在训练时在这个点云中会随机取值，可能会取到重复的值吗？

**Comment by jiangzhangze** [comment]
你好 @HydrogenSulfate ，我现在有个新的问题，如果我的边界条件是随时间和空间变化的，比如说[DFG基准](https://wwwold.mathematik.tu-dortmund.de/~featflow/en/benchmarks/cfdbenchmarking/flow/dfg_benchmark3_re100.html)
其中圆柱绕流的入口边界条件为`u(x,y,t) = 4*1.5*sin(pi*t/8)*y*(0.41-y)/0.41^2`
这种情况下dataset应该怎么生成呢

**Comment by HydrogenSulfate** [comment]
> 你好 @HydrogenSulfate ，我现在有个新的问题，如果我的边界条件是随时间和空间变化的，比如说[DFG基准](https://wwwold.mathematik.tu-dortmund.de/~featflow/en/benchmarks/cfdbenchmarking/flow/dfg_benchmark3_re100.html) 其中圆柱绕流的入口边界条件为`u(x,y,t) = 4*1.5*sin(pi*t/8)*y*(0.41-y)/0.41^2`
> 
> 这种情况下dataset应该怎么生成呢，这种情况下是不是应该把inlet的数据集改成probes的数据集的形式

有两种方法
1. 在 PaddleScience 外面手动生成采样点 $(t,x,y)$，然后生成对应的边界条件 $u_{BC}(t,x,y)$，然后这两者作为文件读入进来作为监督数据，用 `ppsci.constraint.SupervisedConstraint` 包一层变成约束
2. 在 PaddleScience 里面用 Geometry 生成采样点，那么这样对应使用的是 `ppsci.constraint.BoundaryConstraint`，在其参数 `label_dict` 字典里，用函数（或lambda表达式）代替常数即可，如下所示

    ``` python
    ppsci.constraint.BoundaryConstraint(
        output_expr={"u": lambda d: d["u"]},
        label_dict={"u": lambda input: (input["t"] + input["x"] + input["y"])}, # <-- 这里
        geom["noslip_geo"],
        {**train_dataloader_cfg, "batch_size": 5200},
        ppsci.loss.MSELoss("sum"),
        name="no_slip",
    )
    ```
PaddleScience 处理传入参数为函数的代码逻辑在这里：
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/9bb0ed69-8820-4993-b713-10c5b07da788)

**Comment by jiangzhangze** [comment]
好的感谢
