### ISSUE TITLE
is:issue is:open 构建PINN教程中的A tutorial on Darcy flow in porous medium和A tutorial on Lid Driven Cavity flow的文件中的图片有缺失导致意义不明

### ISSUE THREAD

**Issue by cheercao** [PaddlePaddle/PaddleScience#294]
文档中的图片有确实无法看到图片中的信息

**Comment by Ishaan-Chandak** [comment]
Hey can I work on this issue ?

**Comment by HydrogenSulfate** [comment]
hi，你阅读的可能是老版本的文档，现在PaddleScience已经更新为1.0正式版，最新文档请查看这里：https://paddlescience-docs.readthedocs.io/zh/latest/

**Comment by HydrogenSulfate** [comment]
> Hey can I work on this issue ?

Newest documente there: https://paddlescience-docs.readthedocs.io/zh/latest/

**Comment by HydrogenSulfate** [comment]
> 文档中的图片有确实无法看到图片中的信息

darcy flow 和 LDC 案例教程可以看这里：
https://paddlescience-docs.readthedocs.io/zh/latest/zh/examples/darcy2d/
https://paddlescience-docs.readthedocs.io/zh/latest/zh/examples/ldc2d_steady/

**Comment by Ishaan-Chandak** [comment]
Okays I will give it a look 
Thank you @HydrogenSulfate
