### ISSUE TITLE
能否离线安装或者提供容器

### ISSUE THREAD

**Issue by jiangzhangze** [PaddlePaddle/PaddleScience#367]
### 请提出你的问题 Please ask your question

想在校园内网的服务器上安装paddlescience，有没有不用联网安装的方法

**Comment by HydrogenSulfate** [comment]
如果只是为了单纯安装paddlescience，那可以在联网机器上下载好我们提供的 whl 包然后拷贝到服务器上进行安装https://github.com/PaddlePaddle/PaddleScience/releases

如果在paddlescience 安装的基础上，还要使用 Mesh 等复杂几何模块，则需要按照上述步骤安装多个第三方依赖，确实会比较麻烦，近期会尽快制作镜像发布

**Comment by HydrogenSulfate** [comment]
你好，PaddleScience 现已制作了一个 cuda11.6+python3.7的镜像文件，可以按照文档步骤尝试安装这个镜像试试
https://paddlescience-docs.readthedocs.io/zh/latest/zh/install_setup/#11-docker
