### ISSUE TITLE
【快乐开源】为 PaddleScience 添加 DeepONet 案例

### ISSUE THREAD

**Issue by HydrogenSulfate** [PaddlePaddle/PaddleScience#375]
> This project will be mentored by @[HydrogenSulfate](https://github.com/HydrogenSulfate)

## 1. 背景

对于科学计算领域的方程求解问题，基于神经网络拟合任意复杂函数的原理，可以使用模型将方程输入映射到方程的解上从而得到答案。但在 DeepONet 论文中，展示了神经网络实际上具备更强大的能力——拟合任意的非线性连续泛函或非线性运算符，这意味着或许可以训练一次模型求解各种未知方程，而不是为每一个方程分别训练一个“一次性”模型，为此我们希望为 PaddleScience 实现一个 DeepONet 模型并添加对应案例。

### 2.1 代码开发

参考：[PaddleScience文档-贡献指南](https://paddlescience-docs.readthedocs.io/zh/latest/zh/contribute/#_1)

### 2.2 案例撰写

阅读 DeepONet 论文和源代码，理解其原理，基于 2.1 的代码完成模型训练，自行构造适量的测试数据，使用训练完毕的模型进行测试并可视化结果，说明复现代码的有效性和正确性。基于 mkdocs 撰写案例文档，和复现代码一起提交 PR 至 PaddleScience（参考案例：<https://paddlescience-docs.readthedocs.io/zh/latest/zh/examples/viv/> ）

mkdocs 案例预览步骤：

1. 安装 mkdocs 依赖：`pip install -r docs/requirements.txt`
2. 启动 mkdocs 服务：`mkdocs serve -a 127.0.0.1:8686`
3. 点击终端出现的链接，预览并完善撰写的案例文档

## 3. 参考资料

* 论文：[DeepONet: Learning nonlinear operators for identifying differential equations based on the universal approximation theorem of operators](https://arxiv.org/abs/1910.03193)
* 参考代码(pytorch)：<https://github.com/lululxvi/deepxde/blob/master/examples/operator/antiderivative_unaligned.py>
* 参考代码对应案例：<https://deepxde.readthedocs.io/en/latest/demos/operator/antiderivative_unaligned.html>
* PaddleScience API 文档：<https://paddlescience-docs.readthedocs.io/zh/latest/zh/api/arch/>
* PaddleScience 贡献指南：<https://paddlescience-docs.readthedocs.io/zh/latest/zh/contribute/>

**Comment by luotao1** [comment]
@marshall-dteach 已认领

**Comment by marshall-dteach** [comment]
您好，这个数据获取步骤可以讲解一下吗？没有看懂

**Comment by HydrogenSulfate** [comment]
> 您好，这个数据获取步骤可以讲解一下吗？没有看懂

阅读 DeepONet 论文，然后按照参考资料里的参考代码和参考代码对应案例，使用 PaddleScience 复现 DeepONet 案例，并提交 PR 至本 repo

**Comment by HydrogenSulfate** [comment]
> 您好，这个数据获取步骤可以讲解一下吗？没有看懂

数据在 https://drive.google.com/drive/folders/1PbJ2FQp8IeKhAyzOVcKeOEex7mHKyyCX?usp=sharing

**Comment by luotao1** [comment]
@marshall-dteach 

7月6日晚上19:00-20:00，PFCC例会有一个议题是 [HydrogenSulfate](https://github.com/HydrogenSulfate) 分享【PaddleScience-一个统一训练范式的科学计算套件】，有兴趣的话可以来听一下。

点击链接入会，或添加至会议列表：
https://meeting.tencent.com/dm/n3DceaEH0DyX

#腾讯会议：572-650-012
passwd: 0706

PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨框架做贡献，详情可见 https://github.com/luotao1 主页说明。

**Comment by HydrogenSulfate** [comment]
Finished with PR #433 #435
