### ISSUE TITLE
【快乐开源】为 PaddleScience 制作镜像

### ISSUE THREAD

**Issue by HydrogenSulfate** [PaddlePaddle/PaddleScience#377]
> This project will be mentored by @[HydrogenSulfate](https://github.com/HydrogenSulfate)

## 1. 背景

PaddleScience 套件目前提供了 whl 包安装以及直接 git clone 安装两种形式，但在一些特殊工作环境中（如无法联网），依赖安装过程会比较麻烦，因此希望只做一个基于 ubunutu，具备能直接运行 PaddleScience bracket 案例的镜像供用户使用。

## 2. 收益

新增 docker 镜像安装方式，免去安装各种依赖包联网安装问题

### 3.1 制作要求

* 基于 CUDA 11.6
* python version = 3.7
* 含有 develop 版 PaddlePaddle(commit 号指定为 6fde205677a415eae160bcf42420427ed9372f6b)
* 含有 develop 版 PaddleScience(commit 号指定为 6839369b8409da2489c491f1f8d1e61480796293)
* 在安装了 PaddleScience 基本的依赖包的前提下，安装 pysdf、pymesh、open3d 等 ppsci.geometry.Mesh 模块所需的依赖包

### 3.2 镜像正确性验证

跑通 bracket.py 案例，能开始训练即通过验证。运行命令如下

``` sh
git clone https://github.com/PaddlePaddle/PaddleScience.git
cd PaddleScience
git checkout develop
export PYTHONPATH=$PWD:$PYTHONPATH

cd examples/bracket
wget https://paddle-org.bj.bcebos.com/paddlescience/datasets/bracket/bracket_data.tar
tar -xvf bracket_data.tar
python bracket.py
```

**Comment by sanbuphy** [comment]
认领
