### ISSUE TITLE
【PaddlePaddle Hackathon 2】73、增加（2D/3D/ND ）Geometry

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/PaddleScience#38]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 [【PaddlePaddle Hackathon 第二期】任务总览](https://github.com/PaddlePaddle/Paddle/issues/40234)）

【任务内容】

- 任务描述：

1. 增加Circle类型Geometry（2D/3D）

2. 增加 （2D/3D/ND ）Geometry

- 任务难度：中等

【提交内容】

- 设计文档，并提 PR 至 [PaddlePaddle/community](https://github.com/PaddlePaddle/community) 的 rfcs/Science 目录
- 项目 PR

【技术要求】

- 熟悉 Paddle
- 熟练掌握 Python

【参考内容】

1. 不限Nvidia Modulus 几何方法的实现，参考：https://developer.nvidia.com/modulus-downloads

2. DeepXDE参考：https://github.com/lululxvi/deepxde/tree/master/deepxde/geometry

**Comment by jkrescue** [comment]
Q:对于此次73赛题，增加2D/3D/ND几何能详细描述一下吗，是增加例如3D立方体，3D球形，还是做何种程度的支持？

A：短期几乎补充规则化的2D、3D几何外形，如圆、矩形、三角形、球、立方体、圆柱等，并能够按照一定规则排列（eg: 多个圆柱0°、45°、90°等排列）；若可能，也可以尝试对复杂几何外形（CAD工具，如CATIA/ProE...）在PaddleScience中的识别、解析。
