### ISSUE TITLE
关于后处理的问题

### ISSUE THREAD

**Issue by jiangzhangze** [PaddlePaddle/PaddleScience#409]
### 请提出你的问题 Please ask your question

1.想对loss做可视化，如何将train.log中的loss提取出来；
2.PINN预测的流场是以离散的点来排列的，paraview中可视化效果如下：
![image](https://github.com/PaddlePaddle/PaddleScience/assets/99314760/a4d81409-7b97-4574-bac6-c5127215eca6)
如何获得连续的流场，如文档中一样。

**Comment by HydrogenSulfate** [comment]
在paraview里为这个数据添加一个 Delaunay2D  filter 即可

**Comment by jiangzhangze** [comment]
Hi, @HydrogenSulfate ,关于第一点，我发现`solver`中的`train_output_info`的数据类型是`<ppsci.utils.misc.AverageMeter object at 0x00000216EEA5F550>`有什么办法把里面的各个loss输出保存为csv文件吗

**Comment by HydrogenSulfate** [comment]
> Hi, @HydrogenSulfate ,关于第一点，我发现`solver`中的`train_output_info`的数据类型是`<ppsci.utils.misc.AverageMeter object at 0x00000216EEA5F550>`有什么办法把里面的各个loss输出保存为csv文件吗

`train_output_info` 是一个dict，`AverageMeter` 是其 value 的类型，通过滑动均值的方式计算平均 loss，所以没有保存全部的 loss，PaddleScience 没有提供导出 loss 为 csv 格式的功能，可以通过打印每个 step 的 loss，然后把输出重定向到文本文件里，再转成 csv。
