### ISSUE TITLE
Import error,why?

### ISSUE THREAD

**Issue by q769855234** [PaddlePaddle/PaddleScience#45]
I cannot run the example bacause there is no jacobian, hessian etc. in paddle.autograd

**Comment by xingfeng01** [comment]
Perhaps it is a version problem. Please use daily build of PaddlePaddle: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by q769855234** [comment]
> Perhaps it is a version problem. Please use daily build of PaddlePaddle: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

thanks, it runs
