### ISSUE TITLE
【快乐开源】为 PaddleScience 添加 HamiltonianMonteCarlo API

### ISSUE THREAD

**Issue by HydrogenSulfate** [PaddlePaddle/PaddleScience#450]
> This project will be mentored by @[﻿HydrogenSulfate](https://github.com/HydrogenSulfate)

## 1. 背景

概率编程语言 (PPL) 通过将概率与编程语言的表示能力相结合来解决不确定性问题。概率程序是普通确定性计算和代表数据生成过程的随机采样值的混合。将抽象的概率计算转化为随机梯度下降来解决具体优化问题，使概率方法适用于以前难以处理的模型和数据集大小。

### 2.1 个人收益

* 了解概率编程的基本原理和使用概率编程的基本思想和方法
* 掌握开源套件的开发流程和方法

### 2.2 PaddleScience 收益

* 添加一个 HamiltonianMonteCarlo 概率编程 API 到 `ppsci.probability` 模块下(目前 `ppsci` 目录下没有这个 `probability` 模块，本题目的 API 实现完毕后需要新建该模块即可)

### 3.1 安装 PaddleScience

下载安装 PaddleScience 套件：[https://paddlescience-docs.readthedocs.io/zh/latest/zh/install_setup/#121-git](https://paddlescience-docs.readthedocs.io/zh/latest/zh/install_setup/#121-git)

### 3.2 代码开发

使用现有 PaddlePaddle 框架的 API（[PaddlePaddle 概率相关 API 文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distribution/Overview_cn.html)）进行实现，并将实现逻辑包装至合适的函数（假设名字为 `func`），以 `ppsci.probability.func` 的形式供用户调用（[PaddleScience API 文档](https://paddlescience-docs.readthedocs.io/zh/latest/zh/api/arch/)）。

## 3.3 整理代码并提交PR

参考 [PaddleScience文档-贡献指南-整理代码并提交](https://paddlescience-docs.readthedocs.io/zh/latest/zh/development/#3)

## 4. 参考资料

- [tfp.mcmc.HamiltonianMonteCarlo](https://tensorflow.google.cn/probability/overview?hl=zh-cn)
- [Pyro-HMC](https://docs.pyro.ai/en/stable/mcmc.html?highlight=Hamiltonian#hmc)

## 奖励
500 京东卡

**Comment by NKNaN** [comment]
请问该API有具体的需求说明吗，还是说想要把其他的概率编程框架整体迁移过来？

**Comment by HydrogenSulfate** [comment]
> 请问该API有具体的需求说明吗，还是说想要把其他的概率编程框架整体迁移过来？

感谢对 PaddleScience 的关注，暂时只需要参考 tensorflow 和 pyro，实现这一个 API 即可，不需要把其它无关的 内容迁移过来。

**Comment by cxxly** [comment]
> 请问该API有具体的需求说明吗，还是说想要把其他的概率编程框架整体迁移过来？

如果有兴趣、有精力系统化实现概率编程功能，也非常欢迎哈～
