### ISSUE TITLE
安装paddlescience报错

### ISSUE THREAD

**Issue by Duyz232** [PaddlePaddle/PaddleScience#531]
### 问题描述 Issue Description

![NFZFIK}69FB%`%9 )3QZU_4](https://github.com/PaddlePaddle/PaddleScience/assets/110820271/a71ae1fc-9584-4b06-9966-a3c7e6610008)

### 版本&环境信息 Version & Environment Information

PaddlePaddle版本： cpu版0.0.0
系统环境：Ubuntu 20.04.2 
Python版本:3.9.17
GPU：A100，CUDA11.6
执行：python -c "import ppsci; ppsci.run_check_mesh()"时报错：
![NFZFIK}69FB%`%9 )3QZU_4](https://github.com/PaddlePaddle/PaddleScience/assets/110820271/f04d5de2-7381-49d5-987e-b4020816a329)

**Comment by HydrogenSulfate** [comment]
可以确认一下 `ppsci/__init__.py` 是否导入了 `run_check_mesh` 这个函数，如下所示：
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/e0552d20-1ad4-4f72-bbdf-dfac9097037d)

**Comment by HydrogenSulfate** [comment]
> 您好，我这边又出现了新的问题，麻烦帮忙检查一下： ![E{QA6UD%N){E2F9 CP}EYSW](https://user-images.githubusercontent.com/110820271/268916854-ebe90c10-ea55-4687-9817-3f97749ac4a0.png)

看起来是paddle版本比较老，对0-D tensor支持性不太好导致的，建议安装develop版本的paddle

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by Duyz232** [comment]
感谢您的回复，目前已安装成功！
![977c43dd512146d854a3d4dcd51b776](https://github.com/PaddlePaddle/PaddleScience/assets/110820271/066d2e46-35e1-4d90-a784-3dbef3b624e1)
![91d7de5102a386b077b273d5330282b](https://github.com/PaddlePaddle/PaddleScience/assets/110820271/66c118ae-9a6c-4ad4-ae45-3c21cfe50a36)
但是在继续测试时还是会遇到问题：
![2d31bc89bef8e689b8f176417f30aba](https://github.com/PaddlePaddle/PaddleScience/assets/110820271/8cfd590b-51c9-4fdf-872f-dceb07dcf450)

**Comment by HydrogenSulfate** [comment]
> 感谢您的回复，目前已安装成功！ ![977c43dd512146d854a3d4dcd51b776](https://user-images.githubusercontent.com/110820271/268923684-066d2e46-35e1-4d90-a784-3dbef3b624e1.png) ![91d7de5102a386b077b273d5330282b](https://user-images.githubusercontent.com/110820271/268923708-66c118ae-9a6c-4ad4-ae45-3c21cfe50a36.png) 但是在继续测试时还是会遇到问题： ![2d31bc89bef8e689b8f176417f30aba](https://user-images.githubusercontent.com/110820271/268924072-8cfd590b-51c9-4fdf-872f-dceb07dcf450.png)

看起来是用的直接安装包的方式安装导致的，可以先卸载安装包，然后用以下命令从源码安装

``` sh
pip uninstall paddlesci -y

git clone -b develop https://github.com/PaddlePaddle/PaddleScience.git
# 若 github clone 速度比较慢，可以使用 gitee clone
# git clone -b develop https://gitee.com/paddlepaddle/PaddleScience.git

cd PaddleScience
# install paddlesci with editable mode
pip install -e .
```

**Comment by Duyz232** [comment]
问题已解决，感谢您的回复！！

**Comment by HydrogenSulfate** [comment]
> 问题已解决，感谢您的回复！！

感谢对PaddleScience的关注，有任何使用上的问题或者对发现套件本身存在的代码、文档问题，可以随时提issue或者在discussion里讨论
