### ISSUE TITLE
bracket评估命令错误

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleScience#576]
### bug 描述 bug description

https://paddlescience-docs.readthedocs.io/zh/latest/zh/examples/bracket/

```
python bracket.py mode=eval EVAL.pretrained_model_path=https://paddle-org.bj.bcebos.com/paddlescience/models/bracket/bracket_pretrained.pdparams
```
评估命令错误，不能识别的参数
![image](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/6acab694-0447-43ff-8df0-d867194bac95)

**Comment by HydrogenSulfate** [comment]
看报错信息应该是代码比较老导致的，可以拉一下最新的develop代码再运行
