### ISSUE TITLE
如何实现求三阶导数

### ISSUE THREAD

**Issue by gerjf22** [PaddlePaddle/PaddleScience#696]
### 请提出你的问题 Please ask your question

我在计算三阶导数时出了一些问题。

当我需要求 d^3u/dxdy^2 时（即u先对y求二阶导，再对x求一阶导），我先计算 du_yy = hessian(u, y)，再计算 du_yyx = jacobian(du_yy, x)。

报错为：RuntimeError: (Unavailable) The Op add_triple_grad doesn't have any gradop. If you don't intend calculating higher orderderivatives, please set `create_graph`to False.

请问该怎样实现呢？

**Comment by HydrogenSulfate** [comment]
> ### 请提出你的问题 Please ask your question
> 我在计算三阶导数时出了一些问题。
> 
> 当我需要求 d^3u/dxdy^2 时（即u先对y求二阶导，再对x求一阶导），我先计算 du_yy = hessian(u, y)，再计算 du_yyx = jacobian(du_yy, x)。
> 
> 报错为：RuntimeError: (Unavailable) The Op add_triple_grad doesn't have any gradop. If you don't intend calculating higher orderderivatives, please set `create_graph`to False.
> 
> 请问该怎样实现呢？

如果方便的话，是否可以提供一下能触发这个报错的最小可复现代码以及paddle的版本信息呢

终端执行：`python -c "import paddle; paddle.version.show()"` 可以打印出paddle版本信息

**Comment by gerjf22** [comment]
> > ### 请提出你的问题 Please ask your question
> > 我在计算三阶导数时出了一些问题。
> > 当我需要求 d^3u/dxdy^2 时（即u先对y求二阶导，再对x求一阶导），我先计算 du_yy = hessian(u, y)，再计算 du_yyx = jacobian(du_yy, x)。
> > 报错为：RuntimeError: (Unavailable) The Op add_triple_grad doesn't have any gradop. If you don't intend calculating higher orderderivatives, please set `create_graph`to False.
> > 请问该怎样实现呢？
> 
> 如果方便的话，是否可以提供一下能触发这个报错的最小可复现代码以及paddle的版本信息呢
> 
> 终端执行：`python -c "import paddle; paddle.version.show()"` 可以打印出paddle版本信息
> 
> 之前遇到过这个问题，可能是paddle比较老导致的，可以在官网：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html上安装最新的develop版paddle再运行试试看？

我下载了最新的develop版paddle，可以解决问题。感谢你！

**Comment by HydrogenSulfate** [comment]
> > > ### 请提出你的问题 Please ask your question
> > > 我在计算三阶导数时出了一些问题。
> > > 当我需要求 d^3u/dxdy^2 时（即u先对y求二阶导，再对x求一阶导），我先计算 du_yy = hessian(u, y)，再计算 du_yyx = jacobian(du_yy, x)。
> > > 报错为：RuntimeError: (Unavailable) The Op add_triple_grad doesn't have any gradop. If you don't intend calculating higher orderderivatives, please set `create_graph`to False.
> > > 请问该怎样实现呢？
> > 
> > 
> > 如果方便的话，是否可以提供一下能触发这个报错的最小可复现代码以及paddle的版本信息呢
> > 终端执行：`python -c "import paddle; paddle.version.show()"` 可以打印出paddle版本信息
> > 之前遇到过这个问题，可能是paddle比较老导致的，可以在官网：[https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html上安装最新的develop版paddle再运行试试看？](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html%E4%B8%8A%E5%AE%89%E8%A3%85%E6%9C%80%E6%96%B0%E7%9A%84develop%E7%89%88paddle%E5%86%8D%E8%BF%90%E8%A1%8C%E8%AF%95%E8%AF%95%E7%9C%8B%EF%BC%9F)
> 
> 我下载了最新的develop版paddle，可以解决问题。感谢你！

好的，感谢对 PaddleScience 的关注。由于框架迭代速度比较快，之前一直依赖于 develop paddle，近期 2.6 发版之后会切换到该版本上，避免用户使用老版的 develop 遇到问题。
