### ISSUE TITLE
例子中的ldc2d训练时报None

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/PaddleScience#7]
飞桨develop版本，使用这条命令安装的：
!python -m pip install paddlepaddle-gpu==0.0.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html -q 

为了方便，把例子的文件都调到PaddleScience根目录了。

python3.7 ldc2d.py

训练到第14步就开始报None了 

`epoch/num_epoch:  11 / 30000 batch/num_batch:  1 / 1 loss:  5.3213344 eq_loss:  5.321335 bc_loss:  5.810151
epoch/num_epoch:  12 / 30000 batch/num_batch:  1 / 1 loss:  2.547808 eq_loss:  2.547808 bc_loss:  1.0792037
epoch/num_epoch:  13 / 30000 batch/num_batch:  1 / 1 loss:  0.30164686 eq_loss:  0.30164686 bc_loss:  3.5897355
epoch/num_epoch:  14 / 30000 batch/num_batch:  1 / 1 loss:  nan eq_loss:  nan bc_loss:  nan
epoch/num_epoch:  15 / 30000 batch/num_batch:  1 / 1 loss:  nan eq_loss:  nan bc_loss:  nan`

其它两个例子都ok的。

**Comment by levi131** [comment]
你好，感谢试用PaddleScience。
这边根据你使用的安装命令进行了复现，使用2021年11月23日的飞桨develop版本运行结果是正常的。
epoch/num_epoch:  10 / 30000 batch/num_batch:  1 / 1 loss:  5.400353 eq_loss:  0.54816055 bc_loss:  5.3724604
epoch/num_epoch:  11 / 30000 batch/num_batch:  1 / 1 loss:  5.3609276 eq_loss:  0.41878736 bc_loss:  5.344545
epoch/num_epoch:  12 / 30000 batch/num_batch:  1 / 1 loss:  5.254435 eq_loss:  0.24115495 bc_loss:  5.2488985
epoch/num_epoch:  13 / 30000 batch/num_batch:  1 / 1 loss:  5.23064 eq_loss:  0.049767606 bc_loss:  5.230403
epoch/num_epoch:  14 / 30000 batch/num_batch:  1 / 1 loss:  5.2811966 eq_loss:  0.15733919 bc_loss:  5.278852
epoch/num_epoch:  15 / 30000 batch/num_batch:  1 / 1 loss:  5.320041 eq_loss:  0.30631232 bc_loss:  5.311216
epoch/num_epoch:  16 / 30000 batch/num_batch:  1 / 1 loss:  5.312211 eq_loss:  0.39893553 bc_loss:  5.2972107
epoch/num_epoch:  17 / 30000 batch/num_batch:  1 / 1 loss:  5.280262 eq_loss:  0.43080842 bc_loss:  5.2626576
epoch/num_epoch:  18 / 30000 batch/num_batch:  1 / 1 loss:  5.2590795 eq_loss:  0.4056592 bc_loss:  5.243411
epoch/num_epoch:  19 / 30000 batch/num_batch:  1 / 1 loss:  5.257983 eq_loss:  0.33243307 bc_loss:  5.247464
epoch/num_epoch:  20 / 30000 batch/num_batch:  1 / 1 loss:  5.256689 eq_loss:  0.22950773 bc_loss:  5.2516766

之前你那边运行结果不正确可能原因是最近Paddle框架中一些基础算子改动造成的精度问题，现在都已经进行了修复，重新安装一下最新的飞桨develop版本就可以了。

**Comment by skywalk163** [comment]
感谢及时回复，今天用飞桨新版本测试，果然没有问题了！
