### ISSUE TITLE
AI Studio快速体验ldc2d_steady_Re10完整代码出现error

### ISSUE THREAD

**Issue by Chernyn** [PaddlePaddle/PaddleScience#778]
### bug 描述 bug description

for key in vis_interior_points:
&ensp; &ensp;   vis_points[key] = np.concatenate(
&ensp;&ensp;&ensp; &ensp;      (vis_interior_points[key], vis_boundary_points[key])
    &ensp;&ensp;&ensp;)
处代码运行出现error如下:
(vis_interior_points[key], vis_boundary_points[key])
KeyError: 'sdf'

**Comment by HydrogenSulfate** [comment]
已修复，改为 `for key in ["x", "y"]` 即可：https://aistudio.baidu.com/projectdetail/6137973
