### ISSUE TITLE
paddlescience训练模型，验证时出错

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/PaddleScience#800]
### bug 描述 bug description

训练模型时，当到验证结束的时候，会出现错误
![image](https://github.com/PaddlePaddle/PaddleScience/assets/71805205/7e08945b-45c9-48f6-8bea-14dfb99fc207)

修正代码fix:
将ppsci/solver/eval.py 第273行：
metric_value = paddle.concat(metric_value)[:num_samples]，
修改为：
metric_value = paddle.stack(metric_value)[:num_samples]

**Comment by HydrogenSulfate** [comment]
`eval_by_batch`函数和`keep_batch`属性是为了解决FourCastNet评估占用显存过大的问题而设计的，考虑到FourCastNet的样本间相互独立，因此首先为每个batch内的样本计算各自的指标（假设此处单个样本的指标为0-D标量），然后暂不进行reduce操作，从而得到形状为`[batch_size, ]`的batch_metric，最终把每个batch_metric在第0维拼接在一起，得到形状为`[num_samples, ]`的full_metric，再做reduce_sum或其他操作，计算整个dataset的指标。

然后看你的报错看起来是手动设置了Metric的keep_batch属性为True，并且metric的计算返回结果是一个标量，所以导致`concat([标量，标量, ...])`时报错。所以我觉得有可能是因为你的metric.forward函数返回的形状不符合`[batch_size,]`这一要求。

1. 可以尝试设置所有metric的keep_batch为False，
2. 保证metric.forward的返回形状是否是`[batch_size,]`的形式（当然这也许现在看来不一定合理，可以随时在issue里反馈）
