### ISSUE TITLE
【快乐开源】为PaddleScience添加chamfer distance loss

### ISSUE THREAD

**Issue by lijialin03** [PaddlePaddle/PaddleScience#851]
## 1. 背景
点云是一种常见的数据结构，用于表示三维空间中的一组点，Chamfer Distance 是一种用于衡量两个点云之间相似度的度量方法，在三维问题中应用广泛。目前 PaddleScience 中缺少计算该类 loss 的 API，因此需要补充，并进行详细说明。

## 2. 收益
学习点云相关知识和该种点云间距离度量方法，为 PaddleScience 添加相应 loss 函数。

### 3.1 安装 PaddleScience
安装 Paddle：https://paddlescience-docs.readthedocs.io/zh/latest/zh/install_setup/#13-paddlepaddle
安装 PaddleScience(git 源码安装)：https://paddlescience-docs.readthedocs.io/zh/latest/zh/install_setup/#__tabbed_1_1
### 3.2 代码开发
参考代码：https://pytorch3d.readthedocs.io/en/latest/modules/loss.html#pytorch3d.loss.chamfer_distance
进行开发，要求使用 Paddle 和 PaddleScience 中的API，若需要用到其他 python 包，请优先参考 PaddleScience 的 requirements.txt，或进行对应复现。
按照 [3. 编写文档](https://paddlescience-docs.readthedocs.io/zh/latest/zh/development/#3)教程，安装文档渲染插件并渲染文档，用网页打开文档预览链接。
Loss 相关 API 参考文档：https://paddlescience-docs.readthedocs.io/zh/latest/zh/api/loss/loss/
### 3.3 整理代码并提交PR
参考 [PaddleScience文档-贡献指南-整理代码并提交](https://paddlescience-docs.readthedocs.io/zh/latest/zh/development/#4)

## 奖励
500 京东卡

**Comment by HydrogenSulfate** [comment]
closed for PR #871
