### ISSUE TITLE
训练的时候出现反向传播错误

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/PaddleScience#857]
###  训练反向传播报错

平台：ai studio
paddle:2.6.0
![image](https://github.com/PaddlePaddle/PaddleScience/assets/71805205/142b954a-1687-43db-b73b-19fd58153c7f)
有时报这样的错误：
![image](https://github.com/PaddlePaddle/PaddleScience/assets/71805205/53a10386-134f-47d8-a7aa-657fdb4b9e8a)

**Comment by HydrogenSulfate** [comment]
报错的代码位置如下：

https://github.com/PaddlePaddle/Paddle/blob/0359685f29a58d827def3f056dd84c28fbf16725/paddle/phi/infermeta/unary.cc#L4976-L4983

可以确认一下模型前向过程中是否出有出现：某个地方调用了paddle.transpose，而且transpose的perm数组出现了重复的值。

**Comment by Yang-Changhui** [comment]
> 报错的代码位置如下：
> 
> https://github.com/PaddlePaddle/Paddle/blob/0359685f29a58d827def3f056dd84c28fbf16725/paddle/phi/infermeta/unary.cc#L4976-L4983
> 
> 可以确认一下模型前向过程中是否出有出现：某个地方调用了paddle.transpose，而且transpose的perm数组内所有值对x.ndim取模后，是否有重复。

这个之前检查过了，前向网络中没有使用paddle.transpose

**Comment by HydrogenSulfate** [comment]
> > 报错的代码位置如下：
> > https://github.com/PaddlePaddle/Paddle/blob/0359685f29a58d827def3f056dd84c28fbf16725/paddle/phi/infermeta/unary.cc#L4976-L4983
> > 可以确认一下模型前向过程中是否出有出现：某个地方调用了paddle.transpose，而且transpose的perm数组内所有值对x.ndim取模后，是否有重复。
> 
> 这个之前检查过了，前向网络中没有使用paddle.transpose

1. 尝试更换develop版的paddle再运行
2. 设置GLOG_v=4再运行程序，把输出日志重定向到文本中，看一下transpose是哪个反向OP调用了
3. 方便的话可以把aistudio的项目生成一个版本，然后选择“部分公开”再把链接发给我我看一下。

**Comment by Yang-Changhui** [comment]
@HydrogenSulfate 你好，项目“neuraloperator”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/7659466/ecfc1a7461da452eb99bbb8d15e5e2c6

**Comment by HydrogenSulfate** [comment]
> @HydrogenSulfate 你好，项目“neuraloperator”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/7659466/ecfc1a7461da452eb99bbb8d15e5e2c6

初步判断应该是paddle.einsum遇到`...`pattern时的BUG，换成develop就能跑通了。

**Comment by Yang-Changhui** [comment]
> > @HydrogenSulfate 你好，项目“neuraloperator”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/7659466/ecfc1a7461da452eb99bbb8d15e5e2c6
> 
> 初步判断应该是paddle.einsum遇到含`...`的pattern时的BUG，API负责人之前在develop里修过，你换成官网develop就能跑通了。

好的，谢谢。但是，我使用tfno和uno网络跑就没有问题，使用的是相同的einsum

**Comment by HydrogenSulfate** [comment]
> > > @HydrogenSulfate 你好，项目“neuraloperator”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/7659466/ecfc1a7461da452eb99bbb8d15e5e2c6
> > 
> > 
> > 初步判断应该是paddle.einsum遇到含`...`的pattern时的BUG，API负责人之前在develop里修过，你换成官网develop就能跑通了。
> 
> 好的，谢谢。但是，我使用tfno和uno网络跑就没有问题，使用的是相同的einsum

这可能需要定位一下tfno和uno，einsum的输入pattern、运算Tensor的shape、dtype是不是一样的，然后给一个最小复现case。
