### ISSUE TITLE
带有paddle.fft.fftshift网络模型的导出

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/PaddleScience#896]
### 需求描述 Feature Description

请问，现在的动转静支持带有paddle.einsum API的网络吗，我将带有paddle.einsum网络动转静后，预测结果动态图和静态图结果不一样，请问还需要什么特殊配置吗

**Comment by HydrogenSulfate** [comment]
是已有的案例吗？结果的误差能达到多少呢？

**Comment by HydrogenSulfate** [comment]
> 不是已有案例，我查看了已有案例，使用paddle.einsum API的网络好像都没有动转静，是我新复现的tfno网络预测darcy-flow数据集；误差比较大：感觉输入没有进入静态图网络一样 这是静态图预测结果： ![4ab7c36f94228dc69d48b750a7b05fc](https://private-user-images.githubusercontent.com/71805205/329961249-36beb81a-f40a-4179-9cf7-45d8ddaf8dc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODg2NTEsIm5iZiI6MTcxNTU4ODM1MSwicGF0aCI6Ii83MTgwNTIwNS8zMjk5NjEyNDktMzZiZWI4MWEtZjQwYS00MTc5LTljZjctNDVkOGRkYWY4ZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4MTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNWQxNjNiOTkyNTk5ZjU5ZGI1NjFlZTFlOTkwMTU4Y2M1NzI1OWZlZDg0NTUyMDU2YmViMjhhNDhkMTY1MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UaO3pOdFQJ4KAN9_DUA4-xsN6-XBus1-XeZcJi_BIFY)
> 
> 这是动态图预测结果： ![outputs_tfno_pretrain](https://private-user-images.githubusercontent.com/71805205/329960812-df7c7239-e97e-41f6-95f9-eb030c0b08ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODg2NTEsIm5iZiI6MTcxNTU4ODM1MSwicGF0aCI6Ii83MTgwNTIwNS8zMjk5NjA4MTItZGY3YzcyMzktZTk3ZS00MWY2LTk1ZjktZWIwMzBjMGIwOGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4MTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNGM3NTFlZjk4NDdmOWZhM2JjYWUwMTFjM2ZkZmMxNDE1NWU2YjlmYWM3ZjY3NWQzNzg1OTdlOTkxN2RkNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ea-iWaucsaJYz86m3UtEmVxb9UjLOPKXxtLFLu8x1I0)

是否方便在aistudio上提供一下可复现的代码和复现命令

**Comment by Yang-Changhui** [comment]
@HydrogenSulfate 项目“neuraloperator”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/7659466/e8dfd505d4d044e29bf43a751960029b

**Comment by Yang-Changhui** [comment]
@HydrogenSulfate 你好，请问有时间帮忙查一下问题吗

**Comment by HydrogenSulfate** [comment]
> 不是已有案例，我查看了已有案例，使用paddle.einsum API的网络好像都没有动转静，是我新复现的tfno网络预测darcy-flow数据集；误差比较大：感觉输入没有进入静态图网络一样 这是静态图预测结果： ![4ab7c36f94228dc69d48b750a7b05fc](https://private-user-images.githubusercontent.com/71805205/329961249-36beb81a-f40a-4179-9cf7-45d8ddaf8dc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzE3MjgsIm5iZiI6MTcxNTc3MTQyOCwicGF0aCI6Ii83MTgwNTIwNS8zMjk5NjEyNDktMzZiZWI4MWEtZjQwYS00MTc5LTljZjctNDVkOGRkYWY4ZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDExMTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YjVhZGY1MzYyMWI4ZDZhYTdjOWU3YjdhZjExMDE0NDI4NTk0NzJhNjk3Y2ZlZjA4ZTY2ODg0MzAzMGM3YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EVBc34RoOpEoM8BOGwJ9GgIaKOaZYCFQuDLxMN4yF7M)
> 
> 这是动态图预测结果： ![outputs_tfno_pretrain](https://private-user-images.githubusercontent.com/71805205/329960812-df7c7239-e97e-41f6-95f9-eb030c0b08ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzE3MjgsIm5iZiI6MTcxNTc3MTQyOCwicGF0aCI6Ii83MTgwNTIwNS8zMjk5NjA4MTItZGY3YzcyMzktZTk3ZS00MWY2LTk1ZjktZWIwMzBjMGIwOGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDExMTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMjQ5ZWI1M2VlMDg4NjE1MWM2Y2M1ZTYzZjJhYWRiM2Q4ZTEwMGVlZDg1YWE0NzExMjBjN2Y4ODQ5MDhjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6K2fV_-EF45Imiq8EQKA9Jz8gHXMqO5nDmyg-zoUcm4)

1. 某些模型文档里没有导出和推理是因为正在开发中（这段时间会逐步补充完），与einsum无关
2. 我本地试了下含有einsum操作的DeepONet，结果跟动态图的前向完全一致，感觉可能不是einsum的问题
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/23f3166a-fffc-41c9-b104-ed82fe6875a7)，需要进一步确认一下具体是哪个计算过程引入了BUG，可以通过对代码进行二分排查，比如二分点在第100行，那就在forward的第100行直接return结果，然后导出模型-推理，看下结果和动态图是否一致。

**Comment by Yang-Changhui** [comment]
@HydrogenSulfate 好的，谢谢，那我再看看

**Comment by Yang-Changhui** [comment]
@HydrogenSulfate 你好，查出问题出在paddle.fft.fftshift(x=out_fft, axes=fft_dims[:-1])，静态图和动态图输出结果不一样，

**Comment by HydrogenSulfate** [comment]
> @HydrogenSulfate 你好，查出问题出在paddle.fft.fftshift(x=out_fft, axes=fft_dims[:-1])，静态图和动态图输出结果不一样，

收到，我本地测试一下看看
