### ISSUE TITLE
关于LBFGS优化器

### ISSUE THREAD

**Issue by zbyandmoon** [PaddlePaddle/PaddleScience#90]
1. 目前Paddle中添加了minimize_lbfgs函数，虽然可以实现使用 L-BFGS 方法求解可微函数的最小值，但是在训练中不太好用。个人感觉目前实现的功能只是一个high-level的优化函数，这个函数和scipy的minimize(method=’BFGS’)很像，但要用在训练过程中还比较麻烦。我目前用Paddle和PyTorch实现了一个相同的PINNs网络（地址：https://github.com/X4Science/CNN_DSMC/tree/main/Vlasov-PINN），其中需要用到 L-BFGS优化器，使用Paddle我不太清楚怎么在训练中应用minimize_lbfgs，而PyTorch的比较方便，直接可以这样用
![image](https://user-images.githubusercontent.com/41515753/174547179-2c0c8315-3997-4049-b03f-4e39b68719b6.png)
而我看到minimize_lbfgs这个函数中没有网络参数和学习率这两个变量，所以我感觉如果想做成PyTorch这样是不是还需要进一步封装一下？
2. 另外，PyTorch中的L-BFGS优化器在我这个问题的应用中也存在一定的问题，PINNs论文原文显示的是这样的loss曲线
![image](https://user-images.githubusercontent.com/41515753/174549372-991930b0-6edf-4162-8145-004bbabd9f57.png)
但是我应用后的loss曲线是这样的（使用Adam训练10000步，再用LBFGS训练8000步）
![loss](https://user-images.githubusercontent.com/41515753/174549426-3a0eed75-8966-4794-999c-e46bef73d74d.png)
L-BFGS训练过程中的loss是跳动的，且最终收敛的loss值还要高于Adam训练的loss值，但最后反演的方程参数精度提高了。

**Comment by Liu-xiandong** [comment]
你好，目前paddlescience动态图中已经接入了L-BFGS优化器，使用方式可以参考：https://github.com/PaddlePaddle/PaddleScience/blob/develop/examples/laplace/laplace2d.py#L60 。套件中的调用逻辑可以参考：https://github.com/PaddlePaddle/PaddleScience/blob/develop/paddlescience/solver/solver.py#L224 。后续有计划优化paddle中的L-BFGS优化器，欢迎你后续的关注和使用~

**Comment by zbyandmoon** [comment]
收到，谢谢！

**Comment by HydrogenSulfate** [comment]
你好，PaddleScience 1.0 正式版已经发布，提供了全新设计的 API 供开发使用，可以参考用户文档进行开发
https://paddlescience-docs.readthedocs.io/zh/latest/
