### ISSUE TITLE
paddle里LBFGS的使用问题

### ISSUE THREAD

**Issue by whaleprince** [PaddlePaddle/PaddleScience#92]
采用paddle.incubate.optimizer.functional.minimize_lbfgs进行网络训练时，需要提供一个函数func和参数，采用二阶优化方式进行训练的时候，看文档的意思是，损失函数得定义成网络参数的表达式，这怎么实现？

我这里采用闭包定义了一个损失函数，但是训练的时候会报错，请问这个具体该怎么实现？

def train_batch(x, model, loss, weight, optimizer, log_loss, lambda_Re, lambda_Im,):
optimizer.clear_grad()
def clouser():
h = model.feature_transform(x)
w = model(h)
f, t = model.output_transform(x, w)
res = model.pde_(x, h, w, t, f)
opt = model.optim_func(f[:4800], f[:4800])
eqs_loss1 = loss(res[4800:, :1], paddle.zeros_like(res[4800:, :1], dtype='float32'))
eqs_loss2 = loss(res[4800:, 1:], paddle.zeros_like(res[4800:, 1:], dtype='float32'))
lag_loss1 = paddle.mean(res[4800:, :1] * lambda_Re)
lag_loss2 = paddle.mean(res[4800:, 1:] * lambda_Im)
opt_loss = loss(opt, paddle.zeros_like(opt, dtype='float32'))
loss_batch = weight[0] * eqs_loss1 + weight[1] * eqs_loss2 + weight[2] * lag_loss1 + weight[3] * lag_loss2 + weight[4] * opt_loss
log_loss.append([eqs_loss1.item(), eqs_loss2.item(), lag_loss1.item(), lag_loss2.item(), opt_loss.item(),
loss_batch.item()])
return loss_batch
loss_batch =clouser()
loss_batch.backward()
paddle.incubate.optimizer.functional.minimize_lbfgs(clouser, model.parameters())

**报错为：**
paddle.incubate.optimizer.functional.minimize_lbfgs(clouser, model.parameters()[0][0])
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "", line 1, in
paddle.incubate.optimizer.functional.minimize_lbfgs(clouser, model.parameters()[0][0])
File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\incubate\optimizer\functional\lbfgs.py", line 110, in minimize_lbfgs
value, g1 = _value_and_gradient(objective_func, xk)
File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\incubate\optimizer\functional\utils.py", line 92, in _value_and_gradient
value = f(x)
TypeError: clouser() takes 0 positional arguments but 1 was given

**在pytorch里面采用LBFGS算法可以跑通这个模型，pytorch里的优化器模型定义为：**
Optimizer2 = torch.optim.LBFGS(Net_model.parameters(), lr=0.1, max_iter=2)

**训练代码为：**
def train_batch(inn_var, model, loss, weight, optimizer, log_loss, lambda_Re, lambda_Im,):
    def closure():
        optimizer.zero_grad()
        out_var = model(model.feature_transform(inn_var))
        out_var = model.output_transform(inn_var, out_var)
        res = model.pde(inn_var, out_var)
        opt = model.optim_func(inn_var[:4800], out_var[:4800])、
        eqs_loss1 = loss(res[4800:, :1], torch.zeros_like(res[4800:, :1], dtype=torch.float32))
        eqs_loss2 = loss(res[4800:, 1:], torch.zeros_like(res[4800:, 1:], dtype=torch.float32))
        lag_loss1 = torch.mean(res[4800:, :1] * lambda_Re)
        lag_loss2 = torch.mean(res[4800:, 1:] * lambda_Im)
        opt_loss = loss(opt, torch.zeros_like(opt, dtype=torch.float32))
        loss_batch = weight[0] * eqs_loss1 + weight[1] * eqs_loss2 + weight[2] * lag_loss1 + weight[3] * lag_loss2 + \
                     weight[4] * opt_loss
        loss_batch.backward()
        log_loss.append([eqs_loss1.item(), eqs_loss2.item(), lag_loss1.item(), lag_loss2.item(), opt_loss.item(),
                         loss_batch.item()])
        return loss_batch
    optimizer.step(closure)

**Comment by Liu-xiandong** [comment]
你好，目前已经在动态图上接入了LBFGS优化器，调用的example可以参考： https://github.com/PaddlePaddle/PaddleScience/blob/develop/examples/laplace/laplace2d.py#L60

**Comment by yunbattle1994** [comment]
你好~参考 https://github.com/PaddlePaddle/PaddleScience/blob/develop/examples/laplace/laplace2d.py#L60里调用LBFGS优化器得方式，需要先将网络参数提取出来，定义一个以网络参数为输入-损失函数为输出的优化目标函数，再采用LBFGS进行优化。但是，在定义的优化目标函数中，需要采用net.reconstruct()进行一次网络参数重构，而reconstruct函数是定义在FCNet类中的函数。那么在使用LBFGS函数仅能搭配特定的FCNet类才能使用么？如果是自定义的网络该如何实现呢？

**Comment by Liu-xiandong** [comment]
> 

你好，目前LBFGS函数只能搭配FCNet进行使用。我们正在优化LBFGS函数，后续将适用于各种自定义的网络，感谢你的支持~

**Comment by HydrogenSulfate** [comment]
你好，PaddleScience 1.0 正式版已经发布，提供了全新设计的 API 供开发使用，可以参考用户文档进行开发
https://paddlescience-docs.readthedocs.io/zh/latest/
