### ISSUE TITLE
经典案例中Heat_PINN示例代码错误

### ISSUE THREAD

**Issue by leon062112** [PaddlePaddle/PaddleScience#999]
### 文档链接&描述 Document Links&Description

经典案例-技术科学-传热-Heat_PINN：https://paddlescience-docs.readthedocs.io/zh-cn/latest/zh/examples/heat_pinn/
如模型构建代码为：
plt.title("PINN")
plt.xlabel("x")

### 请提出你的建议 Please give your suggestion

请提供正确的参考代码

**Comment by liaoxin2** [comment]
感谢您指出我们文档中的问题。我们已经注意到经典案例中Heat_PINN示例代码的错误，我们会尽快对文档进行检查和修正，确保提供准确无误的示例代码。感谢您的反馈与理解！

**Comment by HydrogenSulfate** [comment]
> 非常感谢！

感谢指出错误，目前代码块定位已经恢复正常
